## Car Price Detection

In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('data/raw/cardekho_imputated.csv')

In [5]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [11]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [13]:
df.drop(['Unnamed: 0','car_name','brand'],axis=1,inplace=True)

In [14]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [16]:
X=df.drop('selling_price',axis=1)
y=df['selling_price']

## Feature Encoding and Standardization

In [19]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X['model']=le.fit_transform(X['model'])

In [20]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

num_features= X.select_dtypes(exclude='object').columns
one_hot_columns=['seller_type','fuel_type','transmission_type']
label_encoder_column=['model']

numeric_transformer=StandardScaler()
oh_transfromer=OneHotEncoder(drop='first')

preprocessor= ColumnTransformer(
    [
        ("OneHotEncoder",oh_transfromer,one_hot_columns),
        ("StandarScaler",numeric_transformer,num_features)
    ],remainder='passthrough' #only categorical features will change
)

In [21]:
X=preprocessor.fit_transform(X)

In [22]:
X=pd.DataFrame(X)

In [23]:
X

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

## Train Test Split

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

## Model Training

In [26]:
from sklearn.ensemble  import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Lasso,ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error

In [34]:
def model_evaluation(true,prediction):
    mae = mean_absolute_error(true,prediction)
    mse = mean_squared_error(true,prediction)
    rmse = np.sqrt(mse)
    score = r2_score(true,prediction)
    return mae,mse,rmse,score

In [43]:
models={
     'LinearRegression': LinearRegression(),
     'Lasso': Lasso(),
     'ElasticNet': ElasticNet(),
     'KNN': KNeighborsRegressor(),
     'DecisionTree': DecisionTreeRegressor(),
     'RandomForest':RandomForestRegressor()
}

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    mae_train,mse_train,rmse_train,rtrain=model_evaluation(y_train,y_train_pred)
    mae_test,mse_test,rmse_test,rtest=model_evaluation(y_test,y_test_pred)
    
    print()
    print(list(models.keys())[i])
    print(f'Mean Square error: {mse_train}')
    print(f'Root Mean Square Error: {rmse_train}')
    print(f'Mean Absolute Error: {mae_train}')
    print(f'R2-Score: {rtrain}')
    print('------------------------')
    
    print('Model Performance on the Test Data')
    print(f'Mean Square error: {mse_test}')
    print(f'Root Mean Square Error: {rmse_test}')
    print(f'Mean Absolute Error: {mae_test}')
    print(f'R2-Score: {rtest}')
    print()

LinearRegression
Mean Square error: 304874315292.8461
Root Mean Square Error: 552154.249547032
Mean Absolute Error: 266675.1075542508
R2-Score: 0.6219860307551311
------------------------
Model Performance on the Test Data
Mean Square error: 270286925822.7529
Root Mean Square Error: 519891.26346069033
Mean Absolute Error: 284283.4459533834
R2-Score: 0.6524693637784766


Lasso
Mean Square error: 304874327628.1807
Root Mean Square Error: 552154.2607172208
Mean Absolute Error: 266674.0471830088
R2-Score: 0.6219860154605374
------------------------
Model Performance on the Test Data
Mean Square error: 270286207881.65326
Root Mean Square Error: 519890.5729878676
Mean Absolute Error: 284283.78899632714
R2-Score: 0.6524702868957395


ElasticNet
Mean Square error: 348939778167.3242
Root Mean Square Error: 590711.2477067998
Mean Absolute Error: 232547.80136331322
R2-Score: 0.5673492191503435
------------------------
Model Performance on the Test Data
Mean Square error: 305783191036.3797
Root Mean Square Error: 552976.6640974822
Mean Absolute Error: 251318.51610952563
R2-Score: 0.6068288297584579


KNN
Mean Square error: 108579261318.56723
Root Mean Square Error: 329513.6739477851
Mean Absolute Error: 90967.36459595086
R2-Score: 0.8653724650130585
------------------------
Model Performance on the Test Data
Mean Square error: 78779566186.25098
Root Mean Square Error: 280676.97836881987
Mean Absolute Error: 116579.3732156761
R2-Score: 0.8987064850635158


DecisionTree
Mean Square error: 426210181.9807348
Root Mean Square Error: 20644.85848778661
Mean Absolute Error: 4991.751744823211
R2-Score: 0.999471541567979
------------------------
Model Performance on the Test Data
Mean Square error: 112034758266.8808
Root Mean Square Error: 334715.9366789708
Mean Absolute Error: 134787.6308504196
R2-Score: 0.855947487282657


RandomForest
Mean Square error: 20014942173.65286
Root Mean Square Error: 141474.17493540247
Mean Absolute Error: 39785.70208468638
R2-Score: 0.9751834531288684
------------------------
Model Performance on the Test Data
Mean Square error: 58555275962.533905
Root Mean Square Error: 241981.9744578796
Mean Absolute Error: 105557.46973002773
R2-Score: 0.9247105562082159